### ISSUE TITLE
no modelshape mat

### ISSUE THREAD

**Issue by ghost** [Fanziapril/mvfnet#1]
I cannot locate the model shape mat file it is not in the 3ddfa zip

**Comment by Fanziapril** [comment]
Please Download the 3DDFA zip and then generate `ModelShape.mat` and `ModelExpression.mat` following their instruction in `readme.txt`.

**Comment by ghost** [comment]
I did download it and unzipped modelexpressesion.mat was there but modelshape.mat is missing

**Comment by Fanziapril** [comment]
After 3DDFA.zip, please generate the Model_Shape.mat following its
readme.txt, which is:
------------------------
How to install the code:
1. Downloading the Basel Face Model (BFM) on "
http://faces.cs.unibas.ch/bfm/main.php?nav=1-0&id=basel_face_model"
2. Copy the "01_MorphableModel.mat" file in the BFM to
Matlab/ModelGeneration/
3. Run the Matlab/ModelGeneration/ModelGenerate.m to generate the shape
model "Model_Shape.mat" and copy it to the Matlab/
------------------------

ak9250 <notifications@github.com> 于 2019年5月27日周一 03:09写道：

**Comment by ghost** [comment]
@Fanziapril I get 
Traceback (most recent call last):
  File "test_img.py", line 5, in <module>
    import tools
  File "/content/mvfnet/tools.py", line 9, in <module>
    model_shape = io.loadmat('data/Model_Shape.mat')
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 65, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/miobase.py", line 241, in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
ValueError: Unknown mat file type, version 57, 54
after getting Model_Shape.mat following steps above 
python test_img.py --image_path ./data/imgs --save_dir ./result

**Comment by ghost** [comment]
@Fanziapril got it working although not sure how to get texture from shape.ply

**Comment by wds1998** [comment]
Please,would you like to tell me how to get model_shape.mat?Or send it to me by e-mail .My e-mail address is wds02467@163.com  Thank you.

**Comment by wds1998** [comment]
I couldn't find 01_MorphableModel.mat in that html.

**Comment by wds1998** [comment]
I solved it ,thank you

**Comment by Dian-Yi** [comment]
> Please,would you like to tell me how to get model_shape.mat?Or send it to me by e-mail .My e-mail address is [wds02467@163.com](mailto:wds02467@163.com) Thank you.

can you share the model_shape.mat to me? thanks a lots

**Comment by Benjaminelee** [comment]
> Please,would you like to tell me how to get model_shape.mat?Or send it to me by e-mail .My e-mail address is [wds02467@163.com](mailto:wds02467@163.com) Thank you.

can you share the model_shape.mat to me? My e-mail address is 2923766880@qq.com. thanks a lots.
