### ISSUE TITLE
how to project the model to front image?

### ISSUE THREAD

**Issue by ReeseL** [Fanziapril/mvfnet#13]
Hi,
Thanks for your excellent work. I want to project the model to the front image of three input images, could you please tell me how to project the model to front image?

Thanks!

**Comment by Fanziapril** [comment]
Hi, 
we provide the front view keypoint projection kptB in https://github.com/Fanziapril/mvfnet/blob/master/tools.py#L66. If you want a projected front image, please refer to some rendering lib.
