### ISSUE TITLE
teeth is not covered by the mesh

### ISSUE THREAD

**Issue by tengshaofeng** [Fanziapril/mvfnet#14]

**Comment by Fanziapril** [comment]
Hi 
Our work is based on Basel Face Model topology, which does not provide teeth mesh.

**Comment by tengshaofeng** [comment]
@Fanziapril thanks for your reply. If I use your work, how could I generate the teeth texture?

**Comment by Fanziapril** [comment]
I am afraid we cannot generate teeth for now. The main reason is we do not have the teeth topology. If you have your own teeth mesh, it could be combined with our face mesh.
