### ISSUE TITLE
Some thing is wrong with shape.ply

### ISSUE THREAD

**Issue by XYWang-coder** [Fanziapril/mvfnet#16]
Hi, I run the example but got such result.
![0](https://user-images.githubusercontent.com/56757249/94418161-98d80600-01b3-11eb-9581-8288efb3d91c.png)
![1](https://user-images.githubusercontent.com/56757249/94418215-aa211280-01b3-11eb-851e-541b3629e499.png)
May I ask how could I solve this problem ?
Thankyou~

**Comment by Fanziapril** [comment]
Hi, the mesh is flipped, you can either rotate the mesh along y axis nor change the light direction in Meshlab.
