### ISSUE TITLE
the .obj format output of test_img.py can't show face color information in meshalb

### ISSUE THREAD

**Issue by 453875726** [Fanziapril/mvfnet#21]
Maybe it's a stupid question...

**Comment by 453875726** [comment]
My 3dmm .ply output is doesn‘t contain the color information of 2d input image.
Anyone knows how to output a colored 3d model like the 2d input image ？
我的3dmm模型得到的.ply文件没有输入2d人脸图像的颜色信息，全是一样的颜色，请问如何解决这个问题？

**Comment by Fanziapril** [comment]
It's right because we actually didn't release the code of texture sampling. Our method is for shape reconstruction and we only sample texture during training.

**Comment by 453875726** [comment]
> 

Thanks for your reply!
