### ISSUE TITLE
Hello, which torchvision I should install for MVF NET?

### ISSUE THREAD

**Issue by daqjjang** [Fanziapril/mvfnet#22]
When I tried to install with pip install torchvision, it kept deleting pytorch 0.4.0 and installing recent version.

**Comment by Benjaminelee** [comment]
I have tried it successed.

conda deactivate
conda remove -n mvfnet --all
conda create -n mvfnet python=2.7
conda activate mvfnet
pip install torch==0.4.0 -i https://pypi.mirrors.ustc.edu.cn/simple/ --no-cache-dir
pip install torchvision==0.2.1 -i https://pypi.mirrors.ustc.edu.cn/simple/ --no-deps
conda install -c 1adrianb face_alignment==1.2.0
pip install pandas -i https://pypi.mirrors.ustc.edu.cn/simple/
