### ISSUE TITLE
Differentiable Rendering

### ISSUE THREAD

**Issue by LeiJiangJNU** [Fanziapril/mvfnet#4]
Thank you for your job.
How to do Differentiable Rendering？Use https://github.com/google/tf_mesh_renderer？

**Comment by Fanziapril** [comment]
Hi, I use the differentiable rendering layer from [this repo](https://github.com/daniilidis-group/neural_renderer). It's a Pytorch implementation of [Neural 3D Mesh Renderer (CVPR 2018)](http://hiroharu-kato.com/projects_en/neural_renderer.html)

**Comment by LeiJiangJNU** [comment]
Thanks for your reply.It help me. Are you going to open source the train code？

**Comment by Fanziapril** [comment]
Our paper is related to a patent so we cannot release the training code at this time.
