### ISSUE TITLE
Performance on florence is inconsistent with the paper

### ISSUE THREAD

**Issue by YuDeng** [Fanziapril/mvfnet#7]
Hi. I've tried your model on florence dataset and do a quantitative experiment. However, in my test your method is worse than Genova et al.. I wonder if there is some limitations i did not notice. For example, do you allow left and right images with large poses (yaw angles larger than 60 degrees) ?  By the way,  florence dataset has multiple images for a single subject under different scenes, do you use only 3 images of a subject for evaluation in your paper?

**Comment by Fanziapril** [comment]
Yes. I randomly chose a left image, a right image and a front image from one video sequence. We only do one inference for each video sequence.
