### ISSUE TITLE
Can anyone provide a download link for modelshape.mat?

### ISSUE THREAD

**Issue by fastcode3d** [Fanziapril/mvfnet#9]
modelshape.mat is hard to get

**Comment by jiaxiangshang** [comment]
1. you need download the 3ddfa code
http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/3DDFA/main.htm
2. you need download bfm09
https://faces.dmi.unibas.ch/bfm/main.php?nav=1-0&id=basel_face_model
3. in the code you can find a dir named as 'ModelGeneration', read the matlab script and you know how to do.

**Comment by tengshaofeng** [comment]
@jiaxiangshang, your advice is really helpful for me. but I have another question.
How could I get a absolute frontal rendered image given the generated 3d face model and a InputB image which is a relative frontal face?

**Comment by jiaxiangshang** [comment]
"absolute frontal rendered image" and "relative frontal face?" is difficult to understand

**Comment by tengshaofeng** [comment]
@jiaxiangshang, 'relative frontal face' is the input rgb image like the Input B in Figure2 in the paper. 'absolute frontal rendered image' is the rendered image I want to get given 3d model and Input B. ok,  I use the following example images to explain.
# 'relative frontal face':![image](https://user-images.githubusercontent.com/9246739/90099991-49a65500-dd6e-11ea-86f3-76ec32d47afc.png)
https://y.taofen8.com/57c9db5f5932478fb57d4e7b1ae77a30.jpg
#  'abosolute frontal face' :
![image](https://user-images.githubusercontent.com/9246739/90100132-a0139380-dd6e-11ea-8d70-0514006082f2.png)
https://y.taofen8.com/e1904c6711bb4aef92265dfb4009dfc0.jpg

sorry， the order is wrong just now

**Comment by jiaxiangshang** [comment]
MVF need input A.B,C 3-view images, then the MVFNet output the 3D mesh. "I want to get given 3d model and Input B" is out of range of 3d face reconstruction, you won't get Input B.

**Comment by tengshaofeng** [comment]
@jiaxiangshang, I know that. What I means is that, when I get the ouput 3D mesh,  how could I render a face in any angle?

**Comment by jiaxiangshang** [comment]
any render pipeline seems can do this

**Comment by tengshaofeng** [comment]
@jiaxiangshang , I am new to 3d face reconstruction and render.  Can you provide some good link to learn render pipeline with  code? thanks so much.

**Comment by jiaxiangshang** [comment]
tf_mesh_render is render pipeline based on deep learning
opengl is a common render pipeline

**Comment by tengshaofeng** [comment]
@jiaxiangshang , ok, thanks

**Comment by Fanziapril** [comment]
> @jiaxiangshang , ok, thanks



> tf_mesh_render is render pipeline based on deep learning
> opengl is a common render pipeline

@tengshaofeng Besides pipeplines suggested by @jiaxiangshang , you can also use a differentiable rendering layer "neural_mesh_renderer", which has pytorch and chainer implementation. For C++ API, openGL is recomended. For me, meshlab is a hands-on visualization tool.

**Comment by tengshaofeng** [comment]
@Fanziapril thansk for your advise.
